FaFitu/FaFitu/Controllers/PhysicalActivityController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace FaFitu.Controllers
{
    public class PhysicalActivityController : Controller
    {
        //
        // GET: /PhysicalActivity/

        public ActionResult Index()
        {
            return View();
        }

    }
}

FaFitu/FaFitu/Controllers/UserPanelController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace FaFitu.Controllers
{
    public class UserPanelController : Controller
    {
        //
        // GET: /UserPanel/

        public ActionResult Index()
        {
            return View();
        }

    }
}

FaFitu/FaFitu/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8" />
        <title>@ViewBag.Title - Fa-Fitu</title>
        <link href="~/favicon.ico" rel="shortcut icon" type="image/x-icon" />
        <meta name="viewport" content="width=device-width" />
        @Styles.Render("~/Content/css")
        @Scripts.Render("~/bundles/modernizr")
    </head>
    <body>
        <header>
            <div class="content-wrapper">
                <div class="float-left">
                    <p class="site-title">@Html.ActionLink("Fa-Fitu", "Index", "Home")</p>
                </div>
                <div class="float-right">
                    <section id="login">
                        @Html.Partial("_LoginPartial")
                    </section>
                    <nav>
                        <ul id="menu">
                        @if (Request.IsAuthenticated) {
                            <li>@Html.ActionLink("Food", "Index", "Food")</li>
                            <li>@Html.ActionLink("Statistics", "Index", "Statistics")</li>
                            <li>@Html.ActionLink("Consumption", "Index", "Consumption")</li>
                            <li>@Html.ActionLink("Physical activity", "Index", "PhysicalActivity")</li>
                            <li>@Html.ActionLink("User panel", "Index", "UserPanel")</li>
                        }
                            <li>@Html.ActionLink("About", "Index", "About")</li>
                        </ul>
                    </nav>
                </div>
            </div>
        </header>
        <div id="body">
            @RenderSection("featured", required: false)
            <section class="content-wrapper main-content clear-fix">
                @RenderBody()
            </section>
        </div>
        <footer>
            <div class="content-wrapper">
                <div class="float-left">
                    <p>&copy; @DateTime.Now.Year - BeFeet</p>
                </div>
            </div>
        </footer>

        @Scripts.Render("~/bundles/jquery")
        @RenderSection("scripts", required: false)
    </body>
</html>